Added function `preprocess_data()` to be imported from `ecog.signal_processing`
BouchardLab/deprecated_process_ecog pull request #4
Opened 2019-05-22 18:02 UTC by luiztauffer

- Preprocess (resamples, filters) the raw data provided in a NWB file
- Runs spectral decomposition for bands in utils/bands.py
- Stores the processed signals and spectral decomposition power values in the same NWB file

2019-05-22 20:41 UTC, bendichter commented
it looks like cfs and sds are not input args

2019-05-22 20:45 UTC, bendichter requested changes
A few minor corrections. Overall it's looking really good!

2019-05-22 20:45 UTC, bendichter commented on ecog/signal_processing/preprocess_data.py
> +    sds: filer standard deviations. If None, use Chang lab defaults
these values are not in the function def

2019-05-22 20:45 UTC, bendichter commented on ecog/signal_processing/preprocess_data.py
> +def transform(block_path, suffix=None, phase=False, seed=20180928):
what is suffix?

2019-05-22 20:51 UTC, luiztauffer commented on ecog/signal_processing/preprocess_data.py
> +    sds: filer standard deviations. If None, use Chang lab defaults
Oh I didn't look at the description, will do it now

2019-05-22 20:53 UTC, luiztauffer commented on ecog/signal_processing/preprocess_data.py
> +def transform(block_path, suffix=None, phase=False, seed=20180928):
it was present in the previous file, it was added at the end of the created file, if the user input something there. I'll remove it

2019-05-22 21:50 UTC, JesseLivezey commented
@luiztauffer @bendichter FYI, we're not planning on maintaining anything in this repo. It's likely that in a few weeks we'll make the current version of our preprocessing code public, which was initially based on the code here. Were you looking to build substantially on this code?

2019-05-22 22:29 UTC, luiztauffer commented
Hi @JesseLivezey   thanks for the heads up!
We’re altering the current process_ecog for two main reasons:
1 – make the preprocessing function directly usable by an [ECoG visualization](https://github.com/bendichter/ecogVIS) project.
2 – make it store the results in NWB files

Would you mind sharing what will be the main changes with the new software? =)

2019-05-28 18:35 UTC, JesseLivezey commented
It might be easier to just copy the preprocessing functions and modify them in your repo. I could also make a different branch and merge them here (I'm using the docker branch for something specific).

The low-level changes to the new version are mostly for operating on arrays that are too large to process in memory all at once. Otherwise, they are the same. The high-level changes are to make the later stages of processing NWB compatible (and also somewhat specific to our lab).

2019-05-28 18:37 UTC, JesseLivezey commented
I can't commit to managing anything in this repo, so it might be better for the other project not to depend on anything here.

2019-05-28 20:00 UTC, closed without merging